### ISSUE TITLE
[FEAT] 공동구매 작성, 삭제 기능 구현

### ISSUE THREAD

**Issue by eggnee** [linavell/TogetherLionRefactoring#2]
## 💡 Feature Issue
공동구매 작성 기능 구현
공동구매 삭제 기능 구현

## 🌿  To-do

- [x] 공동구매 작성 기능 구현
- [x] 공동구매 작성 기능 테스트 작성
- [x] 공동구매 삭제 기능 구현
- [x] 공동구매 삭제 기능 테스트 작성
