### ISSUE TITLE
[FEAT] 공동구매 참여 기능 구현

### ISSUE THREAD

**Issue by eggnee** [linavell/TogetherLionRefactoring#4]
## 💡 Feature Issue
공동구매 참여 기능 구현
공동구매 참여 기능 테스트 코드 작성

## 🌿  To-do

- [ ] 공동구매 참여 기능 구현
- [ ] 공동구매 참여 기능 서비스 테스트 코드 작성
- [ ] 공동구매 참여 기능 컨트롤러 테스트 코드 작성
